# SITE CONFIGURATION
baseurl: ""
url: "//www.timothyrollings.com/"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Timothy Rollings
  avatar:
  favicon:
  gravatar: # Email MD5 hash
  description: "A website adressing topics of machine learning, deep learning, algorithms, and computational neuraoscience." # used by search engines

  # Header and footer text
  header_text: >
    <p><q cite="https://www.brainyquote.com/citation/quotes/geoffrey_hinton_875275">In the long run, curiosity-driven research just works better... Real breakthroughs come from people focusing on what they're excited about.</q></p>
    <footer>—Geoffrey Hinton</footer>
  header_text_feature_image: "assets/img/warhols_neuron_img.png"
  footer_text:
  # Icons
  rss: false
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  gitlab:
  github: "timatom"
  gitter:
  google_plus:
  instagram:
  linkedin: "https://www.linkedin.com/in/timothyrollings"
  email_address: Timothy.A.Rollings@gmail.com
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter:
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup
  search: false # Enable the search feature

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."
  str_search_no_results: "No results found."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate]
exclude:
  - Gemfile
  - Gemfile.lock
