layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

# social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Machine Learning
    web_url: https://github.com/topics/machine-learning
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png

  - name: Deep Learning
  web_url: https://github.com/topics/deep-learning
  image_url: https://user-images.githubusercontent.com/46494899/71755568-2bcc5580-2e59-11ea-9f64-0716e4204ddb.png

  - name: Artificial Intelligence
  web_url: https://github.com/topics/ai
  image_url: https://user-images.githubusercontent.com/46494899/71755484-d09a6300-2e58-11ea-890c-2242cd8923bb.png

  - name: Computational Neural Science
  image_url: https://user-images.githubusercontent.com/46494899/71755967-4c95aa80-2e5b-11ea-8c1b-7fde9ebd6257.png

  - name: TensorFlow
    web_url: https://github.com/tensorflow/tensorflow
    image_url: https://user-images.githubusercontent.com/46494899/71755135-4f8e9c00-2e57-11ea-9ea8-5d9ee1440504.png

theme: jekyll-theme-cayman
